version: '2'
services:
    kava-app:
        image: kava
        external_links:
            - kava-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/kava?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kava-mysql:
        extends:
            file: mysql.yml
            service: kava-mysql
