version: '2'
services:
    kava-mysql:
        container_name: kava-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/kava/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=kava
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
